databases:
  - name: ruby_scout
    ipAllowList: []
    user: ruby_scout
    plan: free

services:
  - type: web
    plan: free
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ruby_scout
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false